name: Release dev container features

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Publish devcontainer features
        uses: devcontainers/action@v1
        with:
          publish-features: true
          base-path-to-features: ./src
          generate-docs: false
